
CREATE PROC [dbo].[ANALYTICS_GET_CHURNED_FOR_TRIP]
@date varchar(20)--e.g 2016-02

AS

BEGIN
	
	EXEC ANALYTICS_INSERT_CURRENT_MONTH_ACTIVE_USER_FOR_TRIP @date
	EXEC ANALYTICS_INSERT_CURRENT_MONTH_RESURRECTED_USER_FOR_TRIP @date

	TRUNCATE TABLE CUSTOMER_CHURNED


	INSERT INTO CUSTOMER_CHURNED (customer_id,period,create_at)

	SELECT customer_id,period,(SELECT TODAY FROM VW_CURRENT_SG_TIME) FROM CUSTOMER_CHURNED_TEMP 
	WHERE CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_ACTIVE)
	AND CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM CUSTOMER_RESURRECTED)

END