CREATE PROCEDURE [dbo].[GetAll_Asm_And_AsmBooking]
	
AS
BEGIN
Select asset_type_management.asset_type_management_id,
asset_type_management.asset_name,asset_type_management.asset_code,asset_type_management.qr_code_value,
--asset_type_management.station_name,
asset_management_booking.start_date,asset_management_booking.end_date,
station.station_name,
campaign.campaign_name,
asset_management_booking.booking_id,
asset_management_booking.asset_type_name,
asset_management_booking.asset_type_code,
asset_management_booking.campaign_id,
asset_management_booking.booked_status,
asset_type_management.scan_start_date,
asset_type_management.scan_end_date
from asset_type_management
LEFT OUTER JOIN 
asset_management_booking On 
asset_type_management.asset_type_management_id = asset_management_booking.asset_type_management_id
and asset_management_booking.booked_status!='false'
Left JOIN campaign On asset_management_booking.campaign_id = campaign.campaign_id
Left JOIN station on station.station_id = asset_type_management .station_id
Order By asset_type_management.asset_type_management_id DESC
END
