
CREATE PROC [dbo].[WINKTAG_GET_ACTIVE_CAMPAIGN]

AS
BEGIN

DECLARE @CURRENT_DATETIME Datetime ;     
EXEC GET_CURRENT_SINGAPORT_DATETIME @CURRENT_DATETIME OUTPUT 

SELECT * FROM winktag_campaign WHERE WINKTAG_STATUS = 1 --and survey_type !='merchant'
--AND CONVERT(DATE,@CURRENT_DATETIME) >= CONVERT(DATE,from_date)
--AND CONVERT(DATE,@CURRENT_DATETIME) <= CONVERT(DATE,to_date)
--AND CAST(@CURRENT_DATETIME as date) >= CAST('2017-07-04' as date) 
--AND CAST(@CURRENT_DATETIME as time) >= '05:30:00'
--AND CAST(@CURRENT_DATETIME as time) >= '00:00:00'
order by position asc;
	 
END


