CREATE TABLE [dbo].[campaign_newdata_log] (
    [Id]                       INT           IDENTITY (1, 1) NOT NULL,
    [action_id]                INT           NOT NULL,
    [campaign_id]              INT           NULL,
    [new_merchant_id]          INT           NULL,
    [new_campaign_name]        NVARCHAR (50) NULL,
    [new_campaign_code]        NVARCHAR (50) NULL,
    [new_campaign_amount]      DECIMAL (18)  NULL,
    [new_sales_code]           NVARCHAR (50) NULL,
    [new_sales_commission]     NVARCHAR (50) NULL,
    [new_total_winks]          DECIMAL (18)  NULL,
    [new_total_winks_amount]   DECIMAL (18)  NULL,
    [new_agency]               BIT           NULL,
    [new_created_at]           DATETIME      NULL,
    [new_updated_at]           DATETIME      NULL,
    [new_cents_per_wink]       DECIMAL (18)  NULL,
    [new_percent_for_wink]     DECIMAL (18)  NULL,
    [new_campaign_start_date]  DATETIME      NULL,
    [new_campaign_end_date]    DATETIME      NULL,
    [new_agency_name]          NVARCHAR (50) NULL,
    [new_wink_purchase_only]   INT           NULL,
    [new_wink_purchase_status] NVARCHAR (50) NULL,
    [new_campaign_status]      VARCHAR (30)  NULL,
    [scan_limit]               INT           DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

