CREATE TABLE [dbo].[campaign] (
    [campaign_id]            INT             IDENTITY (1, 1) NOT NULL,
    [merchant_id]            INT             NOT NULL,
    [campaign_name]          VARCHAR (100)   NOT NULL,
    [campaign_code]          VARCHAR (100)   NOT NULL,
    [campaign_amount]        DECIMAL (20, 2) NULL,
    [sales_code]             VARCHAR (100)   NOT NULL,
    [sales_commission]       DECIMAL (20, 2) NOT NULL,
    [total_winks]            DECIMAL (10, 2) NULL,
    [total_winks_amount]     DECIMAL (20, 2) NOT NULL,
    [agency]                 BIT             NULL,
    [created_at]             DATETIME        NULL,
    [updated_at]             DATETIME        NULL,
    [cents_per_wink]         DECIMAL (5, 2)  NULL,
    [percent_for_wink]       DECIMAL (10, 2) NULL,
    [campaign_start_date]    DATETIME        NULL,
    [campaign_end_date]      DATETIME        NULL,
    [agency_name]            VARCHAR (255)   NULL,
    [wink_purchase_only]     INT             DEFAULT ((0)) NOT NULL,
    [wink_purchase_status]   VARCHAR (50)    NULL,
    [agency_comm]            DECIMAL (10, 2) CONSTRAINT [agency_comm] DEFAULT ((0)) NOT NULL,
    [revenue_share]          DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [campaign_status]        VARCHAR (30)    DEFAULT ('enable') NOT NULL,
    [total_wink_confiscated] INT             DEFAULT ((0)) NOT NULL,
    [scan_limit]             INT             DEFAULT ((0)) NOT NULL,
    [early_expiration]       INT             CONSTRAINT [DF_campaign_early_expiration] DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([campaign_id] ASC)
);

