CREATE TABLE [dbo].[customer_03_10_2017] (
    [customer_id]               INT           IDENTITY (1, 1) NOT NULL,
    [first_name]                VARCHAR (100) NOT NULL,
    [last_name]                 VARCHAR (100) NOT NULL,
    [email]                     VARCHAR (200) NOT NULL,
    [password]                  VARCHAR (200) NOT NULL,
    [gender]                    NCHAR (10)    NULL,
    [date_of_birth]             VARCHAR (100) NULL,
    [auth_token]                VARCHAR (200) NOT NULL,
    [created_at]                DATETIME      NULL,
    [updated_at]                DATETIME      NULL,
    [imob_customer_id]          INT           NOT NULL,
    [phone_no]                  VARCHAR (10)  NULL,
    [status]                    VARCHAR (10)  NOT NULL,
    [group_id]                  VARCHAR (10)  NOT NULL,
    [confiscated_wink_status]   VARCHAR (10)  NOT NULL,
    [subscribe_status]          VARCHAR (10)  NOT NULL,
    [confiscated_points_status] VARCHAR (1)   NULL,
    [sign_in_status]            INT           NOT NULL,
    [customer_password]         VARCHAR (50)  NULL,
    [avatar_id]                 INT           NOT NULL,
    [avatar_image]              VARCHAR (250) NULL,
    [ip_address]                VARCHAR (50)  NULL,
    [ip_scanned]                VARCHAR (50)  NULL,
    [skin_name]                 VARCHAR (50)  NOT NULL,
    [team_id]                   INT           NOT NULL,
    [nick_name]                 VARCHAR (30)  NULL,
    [updated_password_date]     DATETIME      NULL,
    [customer_unique_id]        VARCHAR (200) NULL
);

