CREATE TABLE [dbo].[customer] (
    [customer_id]               INT           IDENTITY (1, 1) NOT NULL,
    [first_name]                VARCHAR (100) NOT NULL,
    [last_name]                 VARCHAR (100) NOT NULL,
    [email]                     VARCHAR (200) NOT NULL,
    [password]                  VARCHAR (200) NOT NULL,
    [gender]                    NCHAR (10)    NULL,
    [date_of_birth]             VARCHAR (100) NULL,
    [auth_token]                VARCHAR (200) NOT NULL,
    [created_at]                DATETIME      NULL,
    [updated_at]                DATETIME      NULL,
    [imob_customer_id]          INT           CONSTRAINT [DF__customer__imob_c__0A9D95DB] DEFAULT ((0)) NOT NULL,
    [status]                    VARCHAR (10)  CONSTRAINT [DF__customer__status__592635D8] DEFAULT ('enable') NOT NULL,
    [group_id]                  VARCHAR (10)  CONSTRAINT [DF__customer__group___68687968] DEFAULT ((1)) NOT NULL,
    [phone_no]                  VARCHAR (16)  NULL,
    [confiscated_wink_status]   VARCHAR (10)  CONSTRAINT [DF__customer__confis__542C7691] DEFAULT ((0)) NOT NULL,
    [subscribe_status]          VARCHAR (10)  CONSTRAINT [DF__customer__subscr__59E54FE7] DEFAULT ((0)) NOT NULL,
    [confiscated_points_status] VARCHAR (255) CONSTRAINT [DF_customer_confiscated_points_status] DEFAULT ((0)) NULL,
    [sign_in_status]            INT           CONSTRAINT [DF__customer__sign_i__4D1564AE] DEFAULT ((0)) NOT NULL,
    [customer_password]         VARCHAR (50)  NULL,
    [avatar_id]                 INT           CONSTRAINT [DF__customer__avarta__575DE8F7] DEFAULT ((1)) NOT NULL,
    [avatar_image]              VARCHAR (200) CONSTRAINT [DF_avatar_image] DEFAULT (N'profile3.png') NOT NULL,
    [ip_scanned]                VARCHAR (50)  NULL,
    [ip_address]                VARCHAR (50)  NULL,
    [skin_name]                 VARCHAR (50)  CONSTRAINT [DF__customer__skin_n__5FBE24CE] DEFAULT ('pink') NOT NULL,
    [nick_name]                 VARCHAR (30)  NULL,
    [team_id]                   INT           CONSTRAINT [DF__customer__team_i__56F3D4A3] DEFAULT ((1)) NOT NULL,
    [WID]                       VARCHAR (50)  NULL,
    [biometric]                 INT           CONSTRAINT [DF_customer_biometric] DEFAULT ((0)) NULL,
    CONSTRAINT [PK__customer__CD65CB85CD239E2C] PRIMARY KEY CLUSTERED ([customer_id] ASC),
    CONSTRAINT [UQ__customer__081E0F6413AA4FE4] UNIQUE NONCLUSTERED ([auth_token] ASC),
    CONSTRAINT [UQ__customer__081E0F64A1700A87] UNIQUE NONCLUSTERED ([auth_token] ASC),
    CONSTRAINT [UQ__customer__AB6E6164C6820505] UNIQUE NONCLUSTERED ([email] ASC),
    CONSTRAINT [UQ__customer__AB6E6164E21B79DC] UNIQUE NONCLUSTERED ([email] ASC)
);

