CREATE TABLE [dbo].[export_details_log] (
    [export_log_id]            INT           IDENTITY (1, 1) NOT NULL,
    [action_id]                INT           NULL,
    [action_time]              DATETIME      NULL,
    [export_content]           VARCHAR (255) NULL,
    [advertiser_name]          VARCHAR (255) NULL,
    [mas_code]                 VARCHAR (255) NULL,
    [search_from]              VARCHAR (255) NULL,
    [search_to]                VARCHAR (255) NULL,
    [campaign_name]            VARCHAR (255) NULL,
    [contract_no]              VARCHAR (255) NULL,
    [wid]                      VARCHAR (50)  NULL,
    [customer_id]              INT           NULL,
    [customer_name]            VARCHAR (255) NULL,
    [customer_email]           VARCHAR (255) NULL,
    [ip_address]               VARCHAR (255) NULL,
    [scanned_ip]               VARCHAR (255) NULL,
    [status]                   VARCHAR (50)  NULL,
    [eVouchers]                VARCHAR (255) NULL,
    [used_status]              VARCHAR (50)  NULL,
    [branch_name]              VARCHAR (255) NULL,
    [branch_id]                INT           NULL,
    [expired]                  VARCHAR (50)  NULL,
    [asset_type]               VARCHAR (255) NULL,
    [qr_code]                  VARCHAR (255) NULL,
    [lucky_draw]               VARCHAR (255) NULL,
    [asset_name]               VARCHAR (255) NULL,
    [asset_code]               VARCHAR (255) NULL,
    [advertiser_email]         VARCHAR (255) NULL,
    [redemption_merchant_name] VARCHAR (255) NULL,
    [phone_no]                 VARCHAR (255) NULL,
    [in_app]                   VARCHAR (255) NULL,
    [subscribe]                VARCHAR (50)  NULL,
    [created_on]               DATETIME      NULL,
    [gateId]                   VARCHAR (100) NULL,
    [refereeCid]               INT           NULL,
    [refereeName]              VARCHAR (255) NULL,
    [refereeEmail]             VARCHAR (255) NULL,
    [referrerCid]              INT           NULL,
    [referrerName]             VARCHAR (255) NULL,
    [referrerEmail]            VARCHAR (255) NULL,
    CONSTRAINT [PK__export_d__B246642DB4624C81] PRIMARY KEY CLUSTERED ([export_log_id] ASC)
);

