CREATE TABLE [dbo].[winkTreats] (
    [winkTreats_id]            INT             IDENTITY (1, 1) NOT NULL,
    [winkTreats_name]          VARCHAR (250)   NULL,
    [merchant_id]              INT             NOT NULL,
    [mas_code]                 VARCHAR (50)    NOT NULL,
    [industry_id]              INT             NULL,
    [winkTreats_qty]           INT             NULL,
    [winkTreats_Des]           VARCHAR (250)   NOT NULL,
    [winkTreats_type]          VARCHAR (50)    NULL,
    [winkTreats_status]        VARCHAR (10)    NOT NULL,
    [winkTreats_image_large]   VARCHAR (250)   NULL,
    [winkTreats_image_small]   VARCHAR (250)   NULL,
    [winkTreats_price]         DECIMAL (10, 2) NOT NULL,
    [winkTreats_xco]           DECIMAL (10, 2) NOT NULL,
    [winkTreats_PaytoMerchant] DECIMAL (10, 2) NOT NULL,
    [winkTreats_evcode]        VARCHAR (250)   NULL,
    [created_id]               INT             NOT NULL,
    [created_at]               DATETIME        NULL,
    [updated_date]             INT             NULL,
    [updated_at]               DATETIME        NULL,
    [from_date]                DATETIME        NULL,
    [to_date]                  DATETIME        NULL,
    [Is_deleted]               BIT             NULL,
    [internal_testing_status]  INT             NOT NULL,
    PRIMARY KEY CLUSTERED ([winkTreats_id] ASC),
    FOREIGN KEY ([industry_id]) REFERENCES [dbo].[industry] ([industry_id]),
    CONSTRAINT [FK__winkTreat__merch__4F92A9FD] FOREIGN KEY ([merchant_id]) REFERENCES [dbo].[merchant] ([merchant_id])
);

