CREATE TABLE [dbo].[wink_account_filtering_olddata_log] (
    [id]                          INT             IDENTITY (1, 1) NOT NULL,
    [action_id]                   INT             NULL,
    [action_email]                VARCHAR (50)    NULL,
    [customer_id]                 INT             NULL,
    [old_registered_email]        VARCHAR (100)   NULL,
    [old_WINKs_in_eWallet]        DECIMAL (10, 2) NULL,
    [old_points_in_eWallet]       DECIMAL (10, 2) NULL,
    [old_last_expired_evoucher]   DATETIME        NULL,
    [old_registered_phone_no]     VARCHAR (10)    NULL,
    [old_whatsapp_phone_no]       VARCHAR (10)    NULL,
    [old_diasbled_date]           DATETIME        NULL,
    [old_whatsapp_received_date]  VARCHAR (40)    NULL,
    [old_email_request_status]    VARCHAR (10)    NULL,
    [old_whatsapp_request_status] VARCHAR (10)    NULL,
    [old_offender_status]         VARCHAR (50)    NULL,
    [old_reason]                  VARCHAR (4000)  NULL,
    [old_confiscated_status]      VARCHAR (10)    NULL,
    [old_confiscation_batch]      VARCHAR (50)    NULL,
    [old_filtering_status]        VARCHAR (50)    NULL,
    [old_unlocked_date]           DATETIME        NULL,
    [old_remark]                  VARCHAR (4000)  NULL,
    [created_at]                  DATETIME        NULL,
    [updated_at]                  DATETIME        NULL,
    [old_enquiry_received_date]   VARCHAR (30)    NULL,
    [old_confiscated_date]        VARCHAR (25)    NULL,
    [enquiry_received_date]       VARCHAR (50)    NULL,
    [old_multiple_account_id]     VARCHAR (30)    NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

