CREATE TABLE [dbo].[wink_account_filtering_import1] (
    [id]                      INT             IDENTITY (1, 1) NOT NULL,
    [customer_id]             INT             NULL,
    [registered_email]        VARCHAR (100)   NULL,
    [WINKs_in_eWallet]        DECIMAL (10, 2) NULL,
    [points_in_eWallet]       DECIMAL (10, 2) NULL,
    [last_expired_evoucher]   DATETIME        NULL,
    [registered_phone_no]     VARCHAR (10)    NULL,
    [whatsapp_phone_no]       VARCHAR (10)    NULL,
    [diasbled_date]           DATETIME        NULL,
    [whatsapp_received_date]  VARCHAR (40)    NULL,
    [email_request_status]    VARCHAR (10)    NULL,
    [whatsapp_request_status] VARCHAR (10)    NULL,
    [offender_status]         VARCHAR (50)    NULL,
    [reason]                  VARCHAR (4000)  NULL,
    [confiscated_status]      VARCHAR (10)    NULL,
    [confiscation_batch]      VARCHAR (50)    NULL,
    [filtering_status]        VARCHAR (50)    NULL,
    [unlocked_date]           DATETIME        NULL,
    [remark]                  VARCHAR (4000)  NULL,
    [created_at]              DATETIME        NULL,
    [updated_at]              DATETIME        NULL,
    [enquiry_received_date]   DATETIME        NULL,
    [confiscated_date]        VARCHAR (25)    NULL,
    [multiple_account_id]     VARCHAR (30)    NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

